import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGenerated1710767904236 implements MigrationInterface {
  name = 'AutoGenerated1710767904236';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "job_offer" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL, "company" varchar NOT NULL, "description" varchar NOT NULL, "location" varchar NOT NULL, "sallary" integer NOT NULL,"daysAgo" integer NOT NULL, "companyBadge" varchar NOT NULL, "duration" varchar NOT NULL, "qualifications" text array NOT NULL, "reviews" text array NOT NULL)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "job_offer"`);
  }
}
